{
    'name': 'Employee Promotion',
    'version': '15.0',
    'summary': 'Payroll Employee Promotion',
    'description': 'Payroll Employee Promotion',
    'category': 'Payroll Localization',
    'author': 'Muhammed Ashraf',
    'website': 'Website',
    'depends': ['web_domain_field', 'jbm_payscale_configuration', 'jbm_employee_custom', 'jbm_hr_overtime',
                'jbm_hr_contract',
                'hr', 'hr_recruitment', 'taqat_hr_appraisal', 'jbm_group_access_right_extended'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/mail_template.xml',
        'data/mail_activity.xml',
        'data/ir_cron.xml',
        'views/employee_promotion.xml',
        'views/employee_view.xml',
        'views/res_config_view.xml',
        'views/promotion_rules_views.xml',
        'views/eligible_for_promotion_views.xml',
        'views/payscale_scheduled_raise_views.xml',
        'views/hr_contract.xml',
    ],
    'installable': True,
    'auto_install': False
}
