# -*- coding: utf-8 -*-
{
    'name': 'Open HRMS Gratuity Settlement',
    'version': '13.0.2.0.1',
    'summary': """Employee Gratuity Settlement""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'category': 'Generic Modules/Human Resources',
    'website': "https://www.openhrms.com",
    'depends': ['base', 'hr', 'hr_payroll', 'jbm_employee_custom','hr_work_entry_contract_enterprise'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequence.xml',
        # 'data/mail_activity.xml',
        # 'data/mail_template.xml',
        'data/cron_job.xml',
        'reports/gratuity_xlsx_report.xml',
        'views/final_settlement_form.xml',
        'views/hr_employee_view.xml',
        # 'views/hr_leave_custom_view.xml',
        # 'views/hr_leave_view.xml',
        'views/hr_gratuity_view.xml',
        'views/furniture_configuration_view.xml',
        'views/hr_gratuity_accounting_configuration.xml',
        # 'views/gratuity_configuration_view.xml',
        # 'views/hr_contract_views.xml',
        # 'views/hr_training_view.xml',
        # 'wizard/custom_report_view.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
