{
    'name': 'Allowance Request Management',
    'version': '13.0',
    'summary': 'Manage Allowance Requests',
    'description': """
        Helps you to manage Allowance Requests of your company's staff.
        """,
    'category': 'Generic Modules/Human Resources',
    'author': "khadrawy, Muhammed Ashraf, Moqbel Elsaidy",
    'company': 'IBS',
    'maintainer': '',
    'website': "https://www.everbsgroup.com/",
    'depends': ['hr', 'hr_contract', 'report_xlsx', 'jbm_hr_sponsor',
                'jbm_world_airport_list', 'jbm_salary_rules',
                'jbm_payscale_configuration', 'hr_holidays'],
    'data': [
        'data/allowance_request_seq.xml',
        'data/allowance_type.xml',
        'data/res_country.xml',
        'data/cron_job.xml',
        'data/mail_template.xml',
        'data/mail_activity.xml',
        'data/salary_rule_allowance.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'reports/allowance_request_xlsx_report.xml',
        'views/allowance_request_views.xml',
        'wizard/allowance_wizard_view.xml',
        'views/academic_year_views.xml',
        'views/allowance_type.xml',
        'views/hr_employee.xml',
        # 'views/hr_payroll.xml',
        'views/payment_lines.xml',
        'views/employee_payscale.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,
}
